project_name: makeslop
version: 2

builds:
  - id: linux
    main: ./cmd/makeslop/
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-X main.version={{.Version}}"
  - id: mac
    main: ./cmd/makeslop/
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.version={{.Version}}"
