metadata:
  maintainers:
    - "Sergey Nesterenko <nestsdev@gmail.com>"
  license: "MIT"
  homepage: "https://github.com/Zwergpro/makeslop"
  commit_author:
    name: zwergpro
    email: nestsdev@gmail.com
    signing:
      enabled: true
      key: "9833038F4AC3B765A90EBBDEEC538E10E9A61141"
      program: gpg2
      format: openpgp

builds:
  - id: linux
    main: cmd/makeslop/
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-X main.version={{.Version}}"
  - id: mac
    main: cmd/makeslop/
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.version={{.Version}}"
